import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir,readFile } from 'node:fs/promises';
import path from 'node:path';
const base=process.env.TEST_URL||'http://127.0.0.1:4173/';
const executablePath=process.env.CHROMIUM_PATH;
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
const artifacts=path.resolve('../../work/browser');await mkdir(artifacts,{recursive:true});
const errors=[];
async function pageFor(context){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});p.on('dialog',d=>d.accept());return p;}
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await pageFor(context);
 await page.goto(base);await page.waitForLoadState('networkidle');await page.locator('.module-card').first().waitFor();assert.equal(await page.locator('.module-card').count(),10);await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
 await page.fill('#search','Excel');assert.equal(await page.locator('.module-card').count(),1);await page.fill('#search','');
 await page.locator('[data-module="a1"]').click();await page.fill('#count','3');await page.locator('#setup button[type="submit"]').click();await page.locator('input[name="answer"]').first().check();await page.locator('[data-action="check"]').click();assert.equal(await page.locator('.feedback').count(),1);assert(await page.locator('input[name="answer"]').first().isDisabled());
 await page.reload();await page.waitForLoadState('networkidle');await page.locator('[data-action="resume"]').click();assert.equal(await page.locator('.feedback').count(),1);
 await page.locator('[data-action="submit"]').click();await page.locator('.grade').waitFor();assert.equal(await page.locator('.review-item').count(),3);
 await page.locator('summary').click();await page.fill('#student','=Student');const dlPromise=page.waitForEvent('download');await page.locator('[data-action="export"]').click();const dl=await dlPromise;const resultPath=path.join(artifacts,'result.json');await dl.saveAs(resultPath);const result=JSON.parse(await readFile(resultPath,'utf8'));assert.equal(result.total,3);assert.equal(result.student,'=Student');
 await page.locator('[data-view="teacher"]').click();await page.selectOption('#module','b3');await page.fill('#count','4');await page.fill('#minutes','1');await page.locator('#teacher-form button[type="submit"]').click();const link=await page.locator('#class-link').inputValue();assert(link.includes('seed='));
 await page.evaluate(()=>window.print=()=>{});await page.locator('[data-action="print-test"]').click();assert.equal(await page.locator('#print-document article').count(),4);const printed=await page.locator('#print-document article h3').allTextContents();await page.locator('[data-action="print-key"]').click();assert.equal(await page.locator('#print-document article strong').count(),4);
 await page.locator('#import').setInputFiles(resultPath);await page.locator('#class-results tbody tr').waitFor();assert.equal(await page.locator('#class-results tbody tr').count(),1);await page.locator('#import').setInputFiles(resultPath);assert.equal(await page.locator('#class-results tbody tr').count(),1);
 const csvPromise=page.waitForEvent('download');await page.locator('[data-action="csv"]').click();const csv=await csvPromise;const csvPath=path.join(artifacts,'class.csv');await csv.saveAs(csvPath);assert((await readFile(csvPath,'utf8')).includes("'=Student"));
 const second=await browser.newContext({viewport:{width:390,height:844}});const mobile=await pageFor(second);await mobile.goto(link);await mobile.waitForLoadState('networkidle');await mobile.locator('#setup button[type="submit"]').click();const active=await mobile.evaluate(()=>JSON.parse(localStorage.getItem('infocomm-v2-session')));assert.equal(active.questions.length,4);assert.deepEqual(active.questions.map(q=>q.q),printed.map(t=>t.replace(/^\d+\. /,'')));assert.equal(active.config.seed,new URL(link).searchParams.get('seed'));
 await mobile.locator('input[name="answer"]').first().check();await mobile.reload();await mobile.waitForLoadState('networkidle');assert.equal(await mobile.locator('input[name="answer"]:checked').count(),1);assert.equal(await mobile.locator('.feedback').count(),0);await mobile.screenshot({path:path.join(artifacts,'mobile-quiz.png'),fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.evaluate(()=>{const s=JSON.parse(localStorage.getItem('infocomm-v2-session'));s.deadline=Date.now()-100;s.started=s.deadline-60000;localStorage.setItem('infocomm-v2-session',JSON.stringify(s));});await mobile.reload();await mobile.waitForLoadState('networkidle');await mobile.locator('.grade').waitFor();assert((await mobile.locator('main').innerText()).includes('Tempo scaduto'));await mobile.reload();await mobile.waitForLoadState('networkidle');assert.equal(await mobile.evaluate(()=>JSON.parse(localStorage.getItem('infocomm-v2-history')).length),1);
 await mobile.goto(base);await mobile.waitForLoadState('networkidle');await mobile.screenshot({path:path.join(artifacts,'mobile-home.png'),fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('[data-view="history"]').click();const backupPromise=page.waitForEvent('download');await page.locator('[data-action="backup"]').click();const backup=await backupPromise;const backupPath=path.join(artifacts,'backup.json');await backup.saveAs(backupPath);await mobile.locator('[data-view="history"]').click();await mobile.locator('#restore').setInputFiles(backupPath);await mobile.getByText('Progressi ripristinati.',{exact:true}).waitFor();assert.equal(await mobile.locator('.history-row').count(),2);
 await mobile.goto(new URL('docente.html',base).href);await mobile.waitForLoadState('networkidle');await mobile.locator('#teacher-form').waitFor();
 assert.deepEqual(errors,[]);console.log('PASS: desktop/mobile, practice feedback, resume, score, exports, shared seed/print, import deduplication, CSV, exam expiry, backup, legacy redirect; no browser errors.');
}finally{await browser.close();}
