"""Genera docs/data/quiz.json verificando i contenuti reali del PDF InfoComm.
Ogni modulo cita la pagina libro di riferimento (pdf_page - 15).
Eseguire da root repo: python scripts/build_quiz_data.py
"""
import json, os, sys
from pypdf import PdfReader

PDF = os.path.join('dist', '20315 - InfoComm.pdf')
OUT = os.path.join('docs', 'data', 'quiz.json')
OFFSET = 15  # pdf_page = pagina libro + 15 (verificato via campionamento)

MODULES_META = [
    ("a1", "A1 · Azienda e sistemi informativi", 2, 44),
    ("a2", "A2 · E-commerce e comunicazione digitale", 46, 99),
    ("a3", "A3 · Marketing web, social e analytics", 100, 149),
    ("a4", "A4 · Reti, networking e cloud", 150, 187),
    ("a5", "A5 · Sicurezza, crittografia e firma digitale", 188, 241),
    ("a6", "A6 · PA digitale, fatture e SPID", 242, 283),
    ("b1", "B1 · Siti web, HTML e CSS", 284, 347),
    ("b2", "B2 · Documenti aziendali con Word", 348, 399),
    ("b3", "B3 · Excel per l'azienda", 400, 449),
    ("b4", "B4 · Audio, video e immagini", 450, 520),
]

# Parole-chiave attese per modulo (devono comparire nel testo estratto)
KEYWORDS = {
    "a1": ["azienda", "sistema informativo", "ERP"],
    "a2": ["e-commerce", "sito web aziendale", "social network"],
    "a3": ["web analytics", "marketing virale", "diritto d'autore"],
    "a4": ["TCP", "ISO-OSI", "cloud"],
    "a5": ["crittografia", "chiave pubblica", "firma digitale"],
    "a6": ["fattura elettronica", "PagoPA", "SPID"],
    "b1": ["HTML", "CSS", "CMS"],
    "b2": ["mail merge", "lettera commerciale", "Google Moduli"],
    "b3": ["Excel", "filtri", "formattazione condizionale"],
    "b4": ["microfono", "Shotcut", "immagini"],
}

# --- 100 domande grounded (10 per modulo), stile INVALSI: 7 multiple + 3 V/F ---
Q = {
"a1": [
 ("m","Secondo il libro, ogni attività svolta in azienda deve essere…",["improvvisata giorno per giorno","programmata con obiettivi, decisioni, modalità e risorse","delegata interamente all'esterno","svolta senza controllo"],1,17),
 ("m","Il sistema informativo aziendale è…",["l'insieme organizzato di informazioni e procedure per gestire l'azienda","solo il software di contabilità","solo i computer dell'ufficio","la rete internet pubblica"],0,18),
 ("m","Il sistema informatico rispetto al sistema informativo è…",["la stessa cosa","la componente automatizzata (hardware+software) del sistema informativo","solo la carta stampata","un obbligo fiscale"],1,20),
 ("m","ERP (Enterprise Resource Planning) indica…",["un social network","un sistema integrato che unifica i processi aziendali (contabilità, magazzino, vendite…)","un antivirus","un formato video"],1,30),
 ("m","Il passaggio a un sistema informativo integrato serve a…",["evitare dati duplicati e avere informazioni coerenti tra reparti","aumentare la carta stampata","rallentare il lavoro","eliminare i backup"],0,45),
 ("m","La customer satisfaction si verifica anche con…",["brevi questionari online agli utenti","il lancio di una moneta","l'oroscopo","il passaparola incontrollato"],0,45),
 ("m","Il Codice ATECO serve a…",["classificare le attività economiche dell'azienda","criptare le password","comprimere i video","formattare l'hard disk"],0,11),
 ("v","Il sistema informativo coincide sempre con il sistema informatico.",False,20),
 ("v","Un ERP integra in un unico database i dati dei vari reparti aziendali.",True,30),
 ("v","Programmare le attività aziendali significa fissare in anticipo obiettivi e risorse.",True,17),
 ("m","L'impresa è…",["un sistema organizzato di persone e beni per produrre e scambiare","un singolo computer","un social network","una tassa"],0,5),
 ("m","Il sistema produttivo trasforma…",["materie prime in prodotti finiti","prodotti in materie prime","idee in tasse","clienti in fornitori"],0,10),
 ("m","La gestione in base agli aspetti distingue…",["aspetto tecnico, finanziario ed economico-patrimoniale","solo l'aspetto estetico","solo gli orari di lavoro","solo i colori del logo"],0,9),
 ("v","Il Codice ATECO 2017 classifica le attività economiche delle imprese.",True,11),
 ("v","Il sistema informatico comprende anche documenti cartacei e procedure manuali.",False,20),
],
"a2": [
 ("m","Un sito vetrina è…",["un sito che presenta l'azienda senza vendere online","un negozio fisico","un virus","un foglio Excel"],0,100),
 ("m","L'e-commerce indica…",["la vendita di beni/servizi tramite internet","la posta cartacea","la TV analogica","il passaparola in piazza"],0,50),
 ("m","Il Web 3.0 / web semantico punta a…",["contenuti comprensibili anche alle macchine, più personalizzati","spegnere internet","solo pagine stampate","niente motori di ricerca"],0,75),
 ("m","I social network per un'azienda sono utili per…",["comunicare, promuovere e gestire la relazione col cliente","nascondere i prodotti","evitare i clienti","sostituire la contabilità"],0,75),
 ("m","Una newsletter aziendale efficace deve…",["essere mirata, sintetica e con call-to-action chiara","essere lunghissima e generica","contenere solo allegati pesanti","essere inviata senza consenso"],0,60),
 ("m","La comunicazione aziendale sul web deve…",["curare immagine, coerenza e reputazione","copiare contenuti altrui senza citarli","ignorare i commenti","pubblicare password"],0,60),
 ("m","Il carrello elettronico serve a…",["raccogliere i prodotti scelti prima del pagamento","contare i dipendenti","misurare il traffico web","archiviare le fatture"],0,50),
 ("v","Vendere online non richiede alcuna gestione di pagamenti e spedizioni.",False,50),
 ("v","Il sito web aziendale svolge anche una funzione pubblicitaria e comunicativa.",True,100),
 ("v","I social vanno gestiti con un piano editoriale e non a caso.",True,75),
 ("m","Per vendere online servono…",["catalogo, carrello, pagamenti e gestione spedizioni","solo un numero di telefono","solo volantini cartacei","solo il passaparola"],0,50),
 ("m","Il web semantico permette…",["contenuti interpretabili anche dalle macchine","di spegnere i server","di eliminare i browser","solo pagine stampate"],0,75),
 ("m","Una campagna social efficace prevede…",["obiettivi, target, piano editoriale e monitoraggio","post a caso senza misura","solo emoticon","profili anonimi"],0,75),
 ("v","L'e-commerce elimina ogni adempimento fiscale e gestionale.",False,50),
 ("v","La reputazione online influenza le scelte dei clienti.",True,60),
],
"a3": [
 ("m","La web analytics è…",["l'analisi dei dati di navigazione per migliorare sito e marketing","la grafica del logo","la stampa dei volantini","la crittografia"],0,125),
 ("m","Metriche classiche di web analytics sono…",["visite, visitatori unici, bounce rate, conversioni","solo il numero di dipendenti","solo il fatturato cartaceo","temperatura e umidità"],0,125),
 ("m","Il marketing virale…",["diffonde il messaggio tramite condivisioni spontanee degli utenti","è un virus informatico","è vietato per legge sempre","riguarda solo la TV"],0,137),
 ("m","Una GIF animata per un prodotto si può realizzare con…",["strumenti online come Imgflip, con uso consapevole","solo con la stampante","senza immagini","senza rispettare licenze"],0,137),
 ("m","Il diritto d'autore in rete tutela…",["opere creative: testi, immagini, musica, video","le password personali","i cavi di rete","i prezzi dei concorrenti"],0,140),
 ("m","Prima di usare un'immagine trovata online bisogna…",["verificarne licenza e diritti di utilizzo","usarla sempre liberamente","cancellarne l'autore","rivenderla"],0,140),
 ("m","Le fasi di un processo di web analytics includono…",["definizione obiettivi, raccolta dati, analisi, azioni correttive","solo l'acquisto del dominio","solo la stampa","niente decisioni"],0,125),
 ("v","Copiare un'immagine protetta senza licenza è sempre lecito se è per la scuola.",False,140),
 ("v","Il bounce rate alto può indicare contenuti poco pertinenti.",True,125),
 ("v","Il marketing virale sfrutta la condivisione degli utenti.",True,137),
 ("m","Il bounce rate indica…",["la % di visitatori che abbandonano dopo una sola pagina","il numero di dipendenti","la temperatura del server","il costo del dominio"],0,125),
 ("m","Le conversioni sono…",["le azioni desiderate: acquisti, iscrizioni, contatti","i virus eliminati","le pagine stampate","i dipendenti assunti"],0,125),
 ("m","Il diritto d'autore tutela l'opera…",["dal momento della creazione, senza formalità","solo se registrata a pagamento","solo per 24 ore","solo all'estero"],0,140),
 ("v","Le metriche da sole bastano: definire gli obiettivi prima è inutile.",False,125),
 ("v","Citare la fonte non basta se la licenza vieta quell'uso.",True,140),
],
"a4": [
 ("m","Un protocollo di rete è…",["un insieme di regole per comunicare tra computer","un antivirus","un cavo elettrico","un social network"],0,150),
 ("m","Il modello ISO-OSI…",["descrive 7 livelli di comunicazione (fisico→applicazione)","è un cavo in fibra","è un sito web","è una stampante"],0,150),
 ("m","Il protocollo TCP/IP…",["è la base di internet: indirizza e affida i pacchetti","serve solo per stampare","è un formato immagine","è un virus"],0,150),
 ("m","L'hosting di un sito significa…",["ospitare le pagine su un server raggiungibile via internet","tenere il sito solo sul PC spento","stampare il sito","inviare il sito per posta"],0,172),
 ("m","L'housing differisce dall'hosting perché…",["il server è di proprietà e ospitato in un data-center","non usa elettricità","è gratuito sempre","non usa internet"],0,172),
 ("m","Il cloud per l'azienda consente…",["risorse scalabili via internet senza server propri","di non fare mai backup","di lavorare solo offline","di eliminare le password"],0,172),
 ("m","La struttura di una rete aziendale prevede…",["client, server, switch/router, cablaggio o Wi-Fi pianificati","solo smartphone personali","nessuna sicurezza","cavi annodati a caso"],0,172),
 ("v","TCP garantisce consegna ordinata e controllo errori, IP si occupa dell'indirizzamento.",True,150),
 ("v","Hosting e housing sono esattamente la stessa cosa.",False,172),
 ("v","Il cloud elimina ogni responsabilità su privacy e backup.",False,172),
],
"a5": [
 ("m","Le minacce naturali ai sistemi sono…",["tempeste, inondazioni, fulmini, incendi, terremoti","solo gli hacker","solo i virus","solo lo spam"],0,190),
 ("m","La crittografia serve a…",["rendere illeggibile un messaggio ai non autorizzati","velocizzare la stampante","comprimere video","creare siti web"],0,210),
 ("m","Nella crittografia asimmetrica…",["si usano chiave pubblica (condivisa) e privata (segreta)","c'è una sola password per tutti","non esistono chiavi","le chiavi sono inutili"],0,210),
 ("m","La firma digitale garantisce…",["autenticità, integrità e non ripudio del documento","l'anonimato totale","la cancellazione del documento","la stampa a colori"],0,235),
 ("m","Un certificato digitale…",["ha scadenza e va rinnovato; lega una chiave a un soggetto","dura per sempre senza rinnovo","è solo cartaceo","non serve a nulla"],0,235),
 ("m","La PEC è…",["posta elettronica certificata con valore legale di raccomandata","posta pubblicitaria","un social network","un antivirus"],0,235),
 ("m","L'autenticazione forte dell'utente richiede…",["credenziali robuste e possibilmente più fattori","la stessa password ovunque","password condivise","nessun controllo"],0,218),
 ("v","Una chiave a 1024 bit può avere validità massima limitata nel tempo e va rinnovata.",True,235),
 ("v","Condividere la propria chiave privata con tutti è una buona pratica.",False,210),
 ("v","Backup e policy di sicurezza riducono i danni da incidenti.",True,190),
],
"a6": [
 ("m","L'AOO (Area Organizzativa Omogenea) nella PA è…",["l'ufficio che gestisce protocollo e documenti in modo omogeneo","un antivirus","un social","un formato video"],0,245),
 ("m","La fattura elettronica…",["è un file strutturato che transita via SDI con valore fiscale","è una semplice scansione senza valore","si invia solo per posta","non esiste in Italia"],0,255),
 ("m","Il 730 precompilato…",["è predisposto dall'Agenzia con dati già noti, da verificare/integrare","si compila solo a penna","non riguarda i lavoratori","è uguale per tutti senza modifiche"],0,255),
 ("m","Il mercato elettronico della PA (MEPA) serve per…",["acquisti pubblici trasparenti e concorrenziali online","vendere auto usate tra privati","giocare online","guardare film"],0,260),
 ("m","PagoPA è…",["il sistema di pagamenti elettronici verso la PA","una banca privata estera","un social network","un virus"],0,280),
 ("m","Lo SPID è…",["l'identità digitale per accedere ai servizi online di PA e privati","una carta fedeltà del supermercato","un antivirus","un cavo di rete"],0,270),
 ("m","L'e-procurement indica…",["gli acquisti di beni/servizi tramite piattaforme digitali","la stampa di cataloghi","le aste in piazza","il baratto"],0,260),
 ("v","La fattura elettronica ha seguito un percorso di avvicinamento digitale in Europa.",True,255),
 ("v","Con PagoPA i pagamenti alla PA diventano semplici, sicuri e trasparenti.",True,280),
 ("v","SPID e CIE permettono di accedere ai servizi online senza nuove credenziali per ogni sito.",True,270),
],
"b1": [
 ("m","HTML è…",["il linguaggio di markup per strutturare le pagine web","un foglio di calcolo","un antivirus","un database"],0,294),
 ("m","I tag di paragrafo e allineamento in HTML…",["si applicano a p/div con valori left, right, center","non esistono","sono solo per la stampa","distruggono la pagina"],0,300),
 ("m","I CSS servono a…",["separare stile e presentazione dal contenuto HTML","scrivere virus","sostituire il server","eliminare internet"],0,314),
 ("m","Una classe CSS .evidenziato…",["si applica con class=\"evidenziato\" a uno o più elementi","funziona solo stampando","non esiste","cancella il testo"],0,320),
 ("m","HTML5 introduce…",["nuovi tag semantici e form avanzati (email, date, validazione)","solo pagine cartacee","niente form","solo bianco e nero"],0,326),
 ("m","Usabilità e accessibilità di un sito significano…",["facile da usare e fruibile da tutti, anche con disabilità","solo bello da vedere","solo veloce","solo pieno di animazioni"],0,292),
 ("m","Un CMS (es. per siti aziendali) permette di…",["creare e gestire contenuti senza scrivere tutto il codice","programmare chip","stampare libri","creare virus"],0,345),
 ("v","In HTML la struttura (tag) e lo stile (CSS) è bene tenerli separati.",True,314),
 ("v","left è il valore di allineamento predefinito del paragrafo.",True,300),
 ("v","Un sito usabile deve confondere l'utente con menu nascosti.",False,292),
],
"b2": [
 ("m","La lettera commerciale deve…",["avere intestazione, oggetto, corpo chiaro e firma","essere senza data né firma","usare solo emoticon","essere illeggibile"],0,348),
 ("m","Il mail merge (stampa unione) serve a…",["produrre lettere personalizzate da un modello + elenco dati","inviare virus","unire due computer","formattare dischi"],0,364),
 ("m","Nel mail merge il documento origine…",["contiene campi collegati ai record (nomi, indirizzi)","è sempre vuoto","non si salva mai","è un video"],0,370),
 ("m","Per verificare le copie del mail merge…",["si naviga tra i record dalla barra dei record","si tira a sorte","si stampa tutto senza controllare","si cancella l'elenco"],0,370),
 ("m","Google Moduli è utile in azienda per…",["raccogliere risposte con questionari online automatizzati","montare video","programmare app","disegnare loghi"],0,395),
 ("m","L'aspetto di un Modulo Google si cambia…",["definendo layout e temi del questionario","solo stampando","mai","con il martello"],0,395),
 ("m","I documenti automatizzati riducono…",["errori e tempi rispetto alla compilazione manuale","la qualità sempre","la sicurezza sempre","la leggibilità"],0,380),
 ("v","La stampa unione collega un modello ai dati di un elenco.",True,364),
 ("v","Una lettera commerciale non ha bisogno di oggetto e firma.",False,348),
 ("v","Con Google Moduli le risposte si raccolgono in modo automatico.",True,395),
],
"b3": [
 ("m","Excel in azienda serve soprattutto a…",["gestire e analizzare dati contabili e commerciali","montare film","navigare anonimi","disegnare fumetti"],0,420),
 ("m","Filtri e subtotali in Excel permettono di…",["selezionare e riepilogare sottoinsiemi di dati","cancellare tutto","formattare il PC","creare virus"],0,420),
 ("m","La formattazione condizionale…",["evidenzia celle in base a regole (es. valori fuori soglia)","cancella i dati","spegne il PC","stampa da sola"],0,420),
 ("m","Funzioni come SOMMA.SE e CONTA.SE servono a…",["sommare/contare solo celle che rispettano criteri","contare i fogli stampati","misurare lo schermo","niente"],0,420),
 ("m","I modelli Excel protetti…",["guidano l'inserimento ed evitano modifiche accidentali","sono inutili","non si salvano","sono virus"],0,445),
 ("m","Un intervallo tipo B2:B2202 indica…",["le celle dalla riga 2 alla 2202 della colonna B","una sola cella","un grafico","una password"],0,445),
 ("m","Applicazioni di marketing in Excel includono…",["analisi vendite, campagne ed expo con tabelle e grafici","solo disegni a mano","niente dati","solo testo libero"],0,451),
 ("v","I filtri mostrano solo le righe che soddisfano i criteri scelti.",True,420),
 ("v","La protezione dei fogli impedisce modifiche alle celle bloccate.",True,445),
 ("v","CONTA.SE conta tutte le celle senza alcun criterio.",False,420),
],
"b4": [
 ("m","Un trasduttore audio come il microfono…",["trasforma onde di pressione in segnali elettrici","cuoce la pasta","stampa foto","proietta film"],0,470),
 ("m","La rappresentazione digitale di suoni/immagini richiede…",["campionamento e quantizzazione in bit","solo carta e penna","niente formati","solo TV analogica"],0,470),
 ("m","Per elaborare immagini (es. sostituire uno sfondo) si usano…",["selezioni e livelli in un editor grafico","solo il blocco note","la calcolatrice","il martello"],0,490),
 ("m","Shotcut è…",["un editor video gratuito per tagliare e montare filmati","un virus","una stampante","un social"],0,510),
 ("m","Aggiungere didascalie e riconoscimenti a un video…",["rispetta autori e migliora la comprensione","è inutile","è vietato","rovina tutto"],0,502),
 ("m","Formati e compressione servono a…",["bilanciare qualità e peso di audio/video/immagini","eliminare i file","non servono","aumentare sempre il peso"],0,485),
 ("m","Un uso consapevole dei media in azienda richiede…",["rispetto di licenze, privacy e diritto d'autore","copie abusive","volti pubblicati senza consenso","musica rubata"],0,490),
 ("v","Il microfono è un esempio di trasduttore audio.",True,470),
 ("v","Comprimere un video riduce sempre e solo la qualità senza vantaggi.",False,485),
 ("v","Nei video aziendali vanno indicati autori e fonti del materiale.",True,502),
],
}

# --- Estensione a 40 domande/modulo (25-30 voci ciascuna, stessi temi del libro) ---
Q_EXTRA = {
"a1": [
 ("m","I dati diventano informazioni quando…",["organizzati e interpretabili per decidere","stampati a caso","cancellati","nascosti"],0,18),
 ("m","Le funzioni aziendali comprendono…",["produzione, commerciale, amministrazione, finanza, personale","solo le pulizie","solo la mensa","solo il parcheggio"],0,2),
 ("m","La funzione commerciale si occupa di…",["vendite, marketing e clienti","assumere operai","produrre energia","guidare i camion"],0,2),
 ("m","La logistica aziendale gestisce…",["flussi di merci e magazzino","solo le email","solo i social","solo le tasse"],0,10),
 ("m","Un sistema informativo di qualità garantisce dati…",["corretti, completi e tempestivi","segreti a tutti","sempre cartacei","senza backup"],0,20),
 ("m","L'hardware è…",["la parte fisica del sistema informatico","un programma","un virus","un documento"],0,20),
 ("m","Il software applicativo è…",["programmi per attività specifiche come contabilità e magazzino","il cavo di rete","la stampante","la scrivania"],0,20),
 ("m","I moduli di un ERP coprono…",["contabilità, magazzino, vendite, acquisti, personale","solo i videogiochi","solo la musica","solo le foto"],0,30),
 ("m","Integrare i sistemi informativi evita…",["duplicazioni e incongruenze tra reparti","di lavorare","di usare il PC","le ferie"],0,45),
 ("m","La direzione usa il sistema informativo per…",["pianificare e controllare la gestione","giocare online","guardare film","chattare"],0,17),
 ("m","Le aziende di servizi offrono…",["prestazioni immateriali","solo mattoni","solo automobili","solo pane"],0,7),
 ("m","Le aziende commerciali…",["acquistano e rivendono merci","coltivano grano","estraggono petrolio","costruiscono case"],0,7),
 ("m","La dimensione aziendale si misura con…",["addetti, fatturato e capitale","il colore del logo","il numero di finestre","l'altezza del palazzo"],0,7),
 ("m","Il magazzino custodisce…",["materie prime e prodotti in attesa","solo i dipendenti","solo i computer","solo i documenti fiscali"],0,10),
 ("m","La trasformazione dei materiali può essere…",["fisica, chimica o di assemblaggio","solo magica","solo virtuale","inesistente"],0,11),
 ("m","Il questionario di customer satisfaction deve essere…",["breve e mirato","lungo 100 pagine","in latino","senza domande"],0,45),
 ("m","Il controllo di gestione…",["verifica i risultati rispetto agli obiettivi","controlla i biglietti del cinema","spegne le luci","apre le porte"],0,9),
 ("m","L'aspetto finanziario riguarda…",["entrate, uscite e fabbisogni di cassa","solo i colori","solo i profumi","solo i suoni"],0,9),
 ("m","Il sistema azienda interagisce con…",["clienti, fornitori, banche e PA","nessuno","solo con sé stesso","solo con i gatti"],0,5),
 ("m","Il capitale di un'azienda è…",["l'insieme dei beni economici a disposizione","il numero di sedie","la targa dell'auto","il nome del fondatore"],0,5),
 ("v","Tutte le aziende hanno scopo di lucro.",False,5),
 ("v","Il sistema informativo esiste anche senza computer.",True,18),
 ("v","ERP significa tenere ogni reparto in database separati.",False,30),
 ("v","Informazioni tempestive migliorano le decisioni.",True,17),
 ("v","Un'azienda è un sistema isolato dall'ambiente esterno.",False,5),
],
"a2": [
 ("m","Il catalogo online deve riportare…",["descrizioni, prezzi, foto e disponibilità","solo barzellette","solo il meteo","solo l'oroscopo"],0,50),
 ("m","Il pagamento con carta online avviene…",["tramite gateway sicuri su pagine HTTPS","urlando il numero al telefono","per posta ordinaria","in contanti al postino"],0,50),
 ("m","Spedizione e reso…",["vanno indicati chiaramente prima dell'acquisto","non esistono online","sono sempre gratis ovunque","si decidono dopo anni"],0,50),
 ("m","Il CRM gestisce…",["relazioni e dati dei clienti","le pulizie","le tasse del vicino","il traffico"],0,60),
 ("m","La segmentazione divide i clienti…",["per bisogni, per offerte mirate","per altezza","per colore degli occhi","a caso"],0,60),
 ("m","Il sito responsive…",["si adatta a PC, tablet e smartphone","funziona solo stampato","non esiste","mostra solo testo"],0,90),
 ("m","I motori di ricerca…",["indicizzano le pagine per parole chiave","vendono scarpe","preparano pizze","riparano auto"],0,90),
 ("m","La SEO migliora…",["la visibilità nei motori di ricerca","il sapore del caffè","il traffico stradale","il meteo"],0,90),
 ("m","La home page deve comunicare subito…",["chi siamo e cosa offriamo","il codice fiscale del webmaster","le previsioni astrali","ricette"],0,90),
 ("m","I banner pubblicitari…",["promuovono prodotti su altri siti","sono tovaglie","sono tende","sono quadri"],0,60),
 ("m","L'email marketing invia…",["offerte mirate a chi ha dato consenso","spam a caso","lettere d'amore","minacce"],0,60),
 ("m","Lo spam è…",["posta indesiderata non richiesta","posta certificata","raccomandata","telegramma"],0,60),
 ("m","Il consenso privacy per la newsletter…",["è obbligatorio prima dell'invio","non serve mai","serve solo in Cina","è vietato"],0,60),
 ("m","Il carrello abbandonato si recupera con…",["promemoria ed email mirate","minacce","preghiere","nulla"],0,50),
 ("m","Le recensioni online…",["influenzano gli acquisti futuri","non le legge nessuno","sono illegali","costano soldi"],0,75),
 ("m","Rispondere alle recensioni negative…",["mostra attenzione al cliente","è vietato","è inutile","peggiora tutto"],0,75),
 ("m","Il profilo social aziendale…",["va aggiornato con regolarità","va aperto e abbandonato","non serve","si compra"],0,75),
 ("m","Il piano editoriale è…",["il calendario dei contenuti da pubblicare","un libro di cucina","un quotidiano","un romanzo"],0,75),
 ("m","La fattura di vendita online…",["documenta fiscalmente la transazione","è un disegno","non esiste","è facoltativa sempre"],0,50),
 ("m","Essere visibili su Google dipende da…",["contenuti di qualità, parole chiave e link","tangenti","fortuna cieca","nepotismo"],0,90),
 ("v","Chi vende online non deve indicare prezzi e condizioni.",False,50),
 ("v","La SEO garantisce il primo posto con un fisso.",False,90),
 ("v","L'email marketing richiede il consenso.",True,60),
 ("v","Le recensioni non influenzano le vendite.",False,75),
 ("v","Il sito responsive funziona bene da smartphone.",True,90),
],
"a3": [
 ("m","Il tasso di conversione è…",["la % di visitatori che compie l'azione desiderata","la temperatura del sito","il numero di pagine","il costo del server"],0,125),
 ("m","I visitatori unici…",["contano ogni persona una sola volta","si contano a ogni clic","sono i dipendenti","non esistono"],0,125),
 ("m","Le pagine viste sono…",["il totale delle pagine caricate","le pagine stampate","le pagine strappate","le pagine nascoste"],0,125),
 ("m","Il tempo di permanenza indica…",["interesse per i contenuti","la lentezza del PC","l'ora di pranzo","il fuso orario"],0,125),
 ("m","Le sorgenti di traffico sono…",["motori, social, dirette e referral","sorgenti d'acqua","fontane","rubinetti"],0,125),
 ("m","Google Analytics…",["raccoglie dati sulla navigazione","vende computer","scrive articoli","fa previsioni meteo"],0,125),
 ("m","I cookie sono…",["piccoli file che ricordano visite e preferenze","biscotti da mangiare","virus sempre","giochi"],0,125),
 ("m","Il banner cookie…",["informa e raccoglie il consenso","pubblicizza biscotti","è illegale","non serve"],0,125),
 ("m","L'A/B test…",["confronta due versioni per scegliere la migliore","un esame del sangue","un test della vista","una gara"],0,125),
 ("m","La landing page è…",["la pagina di atterraggio delle campagne","la pagina iniziale del browser","un errore","un virus"],0,125),
 ("m","La call-to-action…",["invita a un'azione: acquista, iscriviti","chiama un taxi","chiama la mamma","un numero verde"],0,125),
 ("m","Il marketing non convenzionale include…",["guerrilla, virale e ambient","solo TV","solo radio","solo volantini"],0,137),
 ("m","La GIF animata…",["immagine in movimento che cattura attenzione","un formato audio","un virus","un documento"],0,137),
 ("m","I meme aziendali…",["vanno usati con cautela e coerenza","sempre e ovunque","mai spiegati","solo di notte"],0,137),
 ("m","Il product placement…",["prodotti inseriti in video e contenuti","prodotti in vetrina","prodotti scaduti","prodotti rubati"],0,137),
 ("m","Il simbolo © indica…",["tutti i diritti riservati","opera libera","opera anonima","opera scaduta"],0,140),
 ("m","Le licenze Creative Commons…",["permettono riusi a certe condizioni","vietano ogni uso","non esistono","costano milioni"],0,140),
 ("m","Il pubblico dominio…",["opere utilizzabili liberamente","un cinema","una piazza","un teatro"],0,140),
 ("m","La SIAE tutela…",["i diritti degli autori in Italia","i guidatori","i pedoni","i ciclisti"],0,140),
 ("m","Citare la fonte…",["è corretto ma non sempre sufficiente","basta sempre per ogni uso","è vietato","è inutile"],0,140),
 ("v","I cookie servono solo a rallentare il sito.",False,125),
 ("v","La landing page è la pagina di atterraggio di una campagna.",True,125),
 ("v","Un'opera in pubblico dominio è liberamente utilizzabile.",True,140),
 ("v","Le Creative Commons vietano sempre ogni riuso.",False,140),
 ("v","L'A/B test confronta due versioni della stessa pagina.",True,125),
],
"a4": [
 ("m","La LAN è…",["la rete locale di edificio o azienda","una rete mondiale","un satellite","un cavo sottomarino"],0,160),
 ("m","La WAN è…",["rete geografica su grandi distanze","rete di una stanza","un telefono","una radio"],0,160),
 ("m","Internet è…",["una rete di reti mondiale","un singolo computer","un programma","un'azienda"],0,160),
 ("m","L'intranet è…",["la rete privata interna all'azienda","internet pubblica","un social","un gioco"],0,172),
 ("m","L'extranet…",["estende l'intranet a partner e clienti","un nuovo internet","un virus","un film"],0,172),
 ("m","Il cavo UTP è…",["doppino ritorto per reti locali","un cavo elettrico","una corda","un tubo"],0,160),
 ("m","La fibra ottica è…",["veloce e adatta alle lunghe distanze","lenta e obsoleta","solo per lampadari","un tipo di pasta"],0,160),
 ("m","Il Wi-Fi collega…",["senza fili, via onde radio","con fili spinati","via posta","via piccioni"],0,172),
 ("m","Il livello fisico OSI…",["trasmette i bit sul mezzo fisico","scrive le email","disegna siti","stampa"],0,150),
 ("m","Il livello applicazione OSI offre…",["servizi all'utente come HTTP e posta","corrente elettrica","acqua","gas"],0,150),
 ("m","Il DNS…",["traduce nomi in indirizzi IP","stampa documenti","cuoce pizze","lava auto"],0,160),
 ("m","L'URL è…",["l'indirizzo completo di una risorsa web","una password","un codice fiscale","una targa"],0,160),
 ("m","HTTPS rispetto a HTTP…",["cifra la comunicazione, più sicuro","è più lento sempre","non esiste","è un virus"],0,150),
 ("m","FTP serve a…",["trasferire file tra computer","telefonare","giocare","disegnare"],0,150),
 ("m","SMTP/POP/IMAP sono…",["protocolli della posta elettronica","giochi online","social network","antivirus"],0,150),
 ("m","Il firewall…",["filtra il traffico e blocca accessi indesiderati","accelera la stampa","raffredda il PC","fa il caffè"],0,172),
 ("m","Il server DHCP…",["assegna automaticamente gli indirizzi IP","distribuisce panini","stampa etichette","conta i soldi"],0,172),
 ("m","Il backup su cloud è…",["copia di sicurezza su server remoti","copia su carta","fotocopia","non serve"],0,172),
 ("m","Il SaaS è…",["software usato via internet in abbonamento","software gratis per sempre","un hardware","un cavo"],0,172),
 ("m","Il dominio web è…",["il nome registrato per raggiungere il sito","un regno medievale","un documento","una password"],0,172),
 ("m","La banda indica…",["i dati trasmessi al secondo","un gruppo musicale","una strada","una cintura"],0,160),
 ("v","LAN e WAN hanno la stessa estensione.",False,160),
 ("v","Il DNS traduce i nomi in indirizzi IP.",True,160),
 ("v","HTTPS cifra browser-server.",True,150),
 ("v","Il firewall accelera la stampa.",False,172),
 ("v","Il Wi-Fi aziendale va protetto con password robuste.",True,172),
 ("v","L'intranet è aperta a tutta internet.",False,172),
 ("v","Il SaaS va installato su ogni PC.",False,172),
 ("v","La fibra va bene sulle lunghe distanze.",True,160),
 ("v","FTP trasferisce file.",True,150),
],
"a5": [
 ("m","I virus sono…",["programmi dannosi che si replicano","batteri veri","animali","piante"],0,190),
 ("m","I worm si diffondono…",["in rete senza file ospite","solo via posta","solo a mano","mai"],0,190),
 ("m","I trojan…",["sembrano utili ma nascondono malware","cavalli veri","statue","giochi innocui"],0,190),
 ("m","I ransomware…",["cifrano i dati e chiedono riscatto","chiedono amicizia","inviano auguri","fanno sconti"],0,190),
 ("m","Gli spyware…",["spiano attività e dati dell'utente","occhiali da sole","videocamere TV","binocoli"],0,190),
 ("m","L'antivirus…",["rileva e rimuove i malware","cura l'influenza","ripara le auto","innaffia"],0,190),
 ("m","Aggiornare i programmi…",["chiude falle di sicurezza","è inutile","danneggia","rallenta sempre"],0,190),
 ("m","Il firewall personale controlla…",["le connessioni in entrata e uscita","la temperatura","l'umidità","il vento"],0,190),
 ("m","Il phishing usa…",["messaggi falsi per rubare credenziali","canne da pesca","reti da pesca","ami"],0,190),
 ("m","Regola base anti-malware:…",["non aprire allegati sospetti","aprire tutto","cliccare ovunque","disattivare tutto"],0,190),
 ("m","Il backup 3-2-1 prevede…",["3 copie, 2 supporti, 1 fuori sede","3 computer rotti","2 chiavette perse","1 preghiera"],0,190),
 ("m","La cifratura simmetrica usa…",["la stessa chiave per cifrare e decifrare","nessuna chiave","due chiavi","tre chiavi"],0,210),
 ("m","Una chiave più lunga (es. 2048 bit)…",["è più sicura della 1024 bit","è più debole","è uguale","non esiste"],0,210),
 ("m","La firma elettronica semplice è…",["es. credenziali o PIN","sempre su carta","una stretta di mano","un timbro"],0,235),
 ("m","La firma qualificata ha…",["piena validità legale","nessun valore","valore solo morale","valore sportivo"],0,235),
 ("m","La marca temporale certifica…",["data e ora del documento","il peso","il colore","il profumo"],0,235),
 ("m","Il certificato qualificato è rilasciato da…",["certificatori accreditati","chiunque","il vicino","sconosciuti"],0,235),
 ("m","Verificare una firma digitale garantisce…",["documento integro e autentico","sconosciuti","anonimato","segretezza del voto"],0,235),
 ("m","L'OTP è…",["password valida per un solo accesso","password eterna","il nome del cane","un film"],0,218),
 ("m","La doppia autenticazione richiede…",["due prove diverse di identità","due computer","due telefoni","due email"],0,218),
 ("m","Il PIN della firma è…",["il codice segreto del titolare","pubblico","condiviso in ufficio","scritto sul monitor"],0,235),
 ("v","I ransomware chiedono un riscatto.",True,190),
 ("v","L'antivirus da solo basta contro tutto.",False,190),
 ("v","Il phishing imita banche e servizi noti.",True,190),
 ("v","Aggiornare chiude falle dei malware.",True,190),
 ("v","La simmetrica usa la stessa chiave.",True,210),
 ("v","La qualificata ha piena validità legale.",True,235),
 ("v","L'OTP si riusa all'infinito.",False,218),
 ("v","Condividere le password va bene.",False,218),
 ("v","Il backup protegge anche dai ransomware.",True,190),
],
"a6": [
 ("m","Il protocollo informatico…",["registra entrata e uscita dei documenti PA","un medicinale","un insetto","un farmaco"],0,245),
 ("m","La segnatura di protocollo è…",["numero e data identificativi","una firma illeggibile","un timbro rotto","un disegno"],0,245),
 ("m","Il fascicolo digitale raccoglie…",["i documenti di un procedimento","fotografie","canzoni","ricette"],0,245),
 ("m","Il documento informatico è…",["rappresentazione digitale con valore legale","un foglio strappato","un disegno","un sogno"],0,242),
 ("m","La copia conforme digitale…",["equivale all'originale","è sempre falsa","non vale nulla","è un gioco"],0,242),
 ("m","La conservazione digitale…",["mantiene il valore legale nel tempo","butta tutto","dimentica tutto","cancella tutto"],0,245),
 ("m","L'indice IPA è…",["l'anagrafe di PA e gestori pubblici","una mela","un succo","un indice borsistico"],0,245),
 ("m","L'ANPR è…",["l'anagrafe nazionale della popolazione","un'agenzia viaggi","un giornale","una radio"],0,270),
 ("m","Il cassetto fiscale offre…",["servizi online dell'Agenzia delle Entrate","posate","bicchieri","tovaglioli"],0,255),
 ("m","Il 730 è…",["la dichiarazione dei redditi dei lavoratori","un modello di auto","un aereo","un treno"],0,255),
 ("m","Il sostituto d'imposta…",["trattiene le tasse per conto del fisco","un calciatore","un attore","un cantante"],0,255),
 ("m","La CU certifica…",["redditi e ritenute dell'anno","le vacanze","i compleanni","le feste"],0,255),
 ("m","Il codice destinatario SDI…",["a 7 caratteri, per ricevere fatture","il PIN del telefono","la password email","il CAP"],0,255),
 ("m","La fattura di cortesia è…",["copia leggibile senza valore fiscale","l'originale","un regalo","uno sconto"],0,255),
 ("m","Lo scontrino elettronico…",["trasmette i corrispettivi all'Agenzia","un giocattolo","unumo scontrino cartaceo vale di più","non esiste"],0,255),
 ("m","Il POS permette…",["pagamenti con carte in negozio","di posare","di riposare","di sposarsi"],0,280),
 ("m","Il bonifico istantaneo accredita…",["in pochi secondi","in un mese","mai","l'anno prossimo"],0,280),
 ("m","L'home banking è…",["la banca online da PC e smartphone","una banca in casa propria","una cassaforte","un salvadanaio"],0,280),
 ("m","L'app IO riunisce…",["i servizi pubblici sullo smartphone","giochi","film","musica"],0,270),
 ("m","Il fascicolo sanitario elettronico contiene…",["i dati salute consultabili online","le ricette di cucina","le foto","i film"],0,270),
 ("m","La CIE è…",["documento e accesso ai servizi online","solo carta d'identità cartacea","una patente","un passaporto annullato"],0,270),
 ("v","Il protocollo registra solo l'uscita.",False,245),
 ("v","La conservazione mantiene il valore legale.",True,245),
 ("v","Il 730 precompilato non si può modificare.",False,255),
 ("v","Lo SDI recapita le fatture elettroniche.",True,255),
 ("v","PagoPA rende tracciabili i pagamenti.",True,280),
 ("v","La CIE è solo carta senza funzioni digitali.",False,270),
 ("v","L'app IO riunisce i servizi pubblici.",True,270),
 ("v","Il POS accetta pagamenti con carte.",True,280),
 ("v","Il codice destinatario serve per le fatture.",True,255),
],
"b1": [
 ("m","Il tag <p> definisce…",["un paragrafo","un'immagine","un link","un virus"],0,294),
 ("m","I titoli <h1>-<h6>…",["gerarchia dal più al meno importante","sono tutti uguali","non esistono","sono virus"],0,294),
 ("m","Le liste <ul>/<ol> sono…",["puntate e numerate","sempre vuote","vietate","a pagamento"],0,294),
 ("m","Le tabelle <table> organizzano…",["righe e celle di dati","solo immagini","solo video","solo audio"],0,294),
 ("m","Il tag <div> è…",["un contenitore generico","un virus","un'immagine","un link"],0,294),
 ("m","Il tag <span> è…",["un contenitore in linea","un blocco enorme","un virus","un modulo"],0,294),
 ("m","Il CSS incorporato in <style>…",["mette gli stili nella pagina","elimina la pagina","crea virus","stampa"],0,314),
 ("m","Il foglio esterno è…",["un file .css collegato con <link>","un foglio di carta","un lenzuolo","una tovaglia"],0,314),
 ("m","I selettori di classe .nome…",["si riusano su più elementi","unici per pagina","non esistono","vietati"],0,320),
 ("m","I selettori di id #nome…",["identificano un elemento unico","si ripetono ovunque","non esistono","sono virus"],0,314),
 ("m","Il selettore di tag stilizza…",["tutti gli elementi di quel tipo","un solo pixel","niente","tutto il web"],0,314),
 ("m","Il box model comprende…",["contenuto, padding, bordo, margine","solo il bordo","solo il contenuto"," scatole vere"],0,314),
 ("m","Il padding è…",["lo spazio interno al bordo","lo spazio esterno","un cuscino vero","un materasso"],0,314),
 ("m","Il margine è…",["lo spazio esterno al bordo","lo spazio interno","un quadro","una cornice vera"],0,314),
 ("m","I colori CSS si scrivono con…",["nomi, esadecimali o rgb","solo parole","solo numeri romani","emoji"],0,314),
 ("m","I font definiscono…",["famiglie e dimensioni del testo","il profumo","il sapore","il peso"],0,314),
 ("m","Il form <form>…",["raccoglie dati da inviare","mostra film","suona musica","disegna"],0,326),
 ("m","L'input text è…",["un campo di testo libero","una password","un bottone","un'immagine"],0,326),
 ("m","L'input email…",["controlla il formato dell'indirizzo","invia da solo","non esiste","è un virus"],0,326),
 ("m","L'input date…",["selettore di data con calendario","orologio","sveglia","timer"],0,326),
 ("m","L'attributo required…",["rende obbligatoria la compilazione","è decorativo","non esiste","blocca tutto"],0,326),
 ("v","I tag HTML sono case sensitive per il browser.",False,294),
 ("v","Ogni pagina dovrebbe avere un solo <h1>.",True,294),
 ("v","Le classi si riusano su più elementi.",True,320),
 ("v","Lo stesso id va ripetuto ovunque.",False,314),
 ("v","Il padding è lo spazio esterno al bordo.",False,314),
 ("v","Il form raccoglie dati da inviare.",True,326),
 ("v","Required obbliga la compilazione.",True,326),
 ("v","Il foglio esterno separa stile e contenuto.",True,314),
 ("v","I colori si scrivono anche in esadecimale.",True,314),
],
"b2": [
 ("m","L'intestazione della lettera riporta…",["il mittente in alto","il meteo","l'oroscopo","barzellette"],0,348),
 ("m","Dopo l'intestazione viene…",["nome e indirizzo del destinatario","la lista della spesa","una poesia","un cruciverba"],0,348),
 ("m","La data nella lettera…",["colloca il documento nel tempo","è decorativa","non serve","è segreta"],0,348),
 ("m","I riferimenti (Prot. n.)…",["identificano la pratica","sono numeri a caso","non servono","sono password"],0,348),
 ("m","Il corpo della lettera è…",["il messaggio chiaro e cortese","un insulto","vuoto","illeggibile"],0,348),
 ("m","I saluti finali sono…",["la chiusura formale","un addio per sempre","inutili","vietati"],0,348),
 ("m","La firma riporta…",["nome e ruolo del mittente","una X","uno scarabocchio","niente"],0,348),
 ("m","Gli allegati…",["si elencano in calce","si nascondono","si buttano","non esistono"],0,348),
 ("m","Il foglio intestato è…",["carta con logo aziendale","carta igienica","carta da parati","carta carbone"],0,348),
 ("m","I modelli di Word sono…",["basi pronte per documenti ricorrenti","giochi","virus","canzoni"],0,364),
 ("m","Gli stili di Word danno…",["formattazione coerente ai titoli","colori a caso","errori","virus"],0,364),
 ("m","Il sommario automatico è…",["l'indice generato dai titoli stilizzati","scritto a mano","un disegno","impossibile"],0,364),
 ("m","Il controllo ortografico…",["segnala errori di scrittura","scrive da solo","cancella tutto","non esiste"],0,364),
 ("m","Il copia formato…",["replica la formattazione","copia i virus","fotocopia","duplica il PC"],0,364),
 ("m","La stampa unione parte da…",["documento modello + origine dati","due stampanti","nessun dato","un fax"],0,364),
 ("m","I campi unione sono…",["segnaposto dei dati nel modello","buchi nella carta","errori","macchie"],0,364),
 ("m","L'anteprima risultati mostra…",["le copie prima di stampare","il futuro","il passato","niente"],0,370),
 ("m","Filtrare i record permette di…",["stampare solo alcuni destinatari","stampare di più","non stampare","rovinare tutto"],0,370),
 ("m","Le etichette servono per…",["indirizzi da elenco per spedizioni","vestiti","valigie","quaderni"],0,370),
 ("m","Google Moduli raccoglie…",["risposte in tempo reale","farfalle","francobolli","figurine"],0,395),
 ("m","Le domande a scelta offrono…",["una o più risposte possibili","nessuna risposta","risposte segrete","solo insulti"],0,395),
 ("v","La lettera non ha bisogno di data.",False,348),
 ("v","Gli allegati vanno elencati.",True,348),
 ("v","Gli stili rendono coerenti i documenti.",True,364),
 ("v","Il sommario usa gli stili titolo.",True,364),
 ("v","La stampa unione crea una copia per record.",True,364),
 ("v","I campi unione restano vuoti per sempre.",False,364),
 ("v","Con i filtri si stampano solo record scelti.",True,370),
 ("v","Google Moduli funziona solo offline.",False,395),
 ("v","Le risposte si vedono in tempo reale.",True,395),
],
"b3": [
 ("m","La cella è…",["l'incrocio di riga e colonna","un insetto","una prigione","una batteria"],0,420),
 ("m","L'indirizzo A1 indica…",["colonna A, riga 1","il primo voto","un'autostrada","una vitamina"],0,420),
 ("m","La barra della formula…",["mostra e modifica il contenuto","una sbarra di ferro","un dolce","un gioco"],0,420),
 ("m","I fogli di lavoro sono…",["le pagine della cartella","fogli di carta","lenzuola","tovaglie"],0,420),
 ("m","SOMMA…",["somma un intervallo di celle","sottrae","moltiplica","divide"],0,420),
 ("m","MEDIA calcola…",["la media aritmetica","la somma","il massimo","il minimo"],0,420),
 ("m","MAX/MIN trovano…",["il valore maggiore/minore","la media","la somma","il conteggio"],0,420),
 ("m","CONTA.NUMERI…",["conta le celle numeriche","conta tutto","conta niente","conta i fogli"],0,420),
 ("m","SE…",["restituisce esiti diversi per condizione","saluta","dorme","corre"],0,420),
 ("m","E/O…",["combinano più condizioni","congiunzioni inutili","errori","virus"],0,420),
 ("m","CERCA.VERT…",["cerca un valore in una tabella","cerca funghi","cerca amici","cerca lavoro"],0,435),
 ("m","Il riferimento relativo A1…",["si adatta copiando la formula","non cambia mai","si rompe","scompare"],0,435),
 ("m","Il $ nei riferimenti…",["blocca riga/colonna nella copia","indica dollari","è decorativo","un errore"],0,435),
 ("m","L'ordinamento…",["riordina le righe per colonna","mette in disordine","cancella","nasconde tutto"],0,420),
 ("m","I duplicati…",["si individuano e rimuovono","si moltiplicano","si nascondono","si celebrano"],0,420),
 ("m","Il formato data mostra…",["giorni, mesi e anni","solo ore","solo minuti","frazioni"],0,420),
 ("m","Il formato percentuale mostra…",["valori per cento","soldi","gradi","litri"],0,420),
 ("m","Bordi e sfondi migliorano…",["la leggibilità delle tabelle","il sapore","il profumo","il suono"],0,420),
 ("m","Blocca riquadri tiene…",["le intestazioni sempre visibili","il PC acceso","la porta chiusa","il cane legato"],0,445),
 ("m","In stampa si impostano…",["area di stampa e righe da ripetere","il volume","la luminosità","il canale"],0,445),
 ("m","Proteggere il foglio con password…",["evita modifiche accidentali","lo nasconde per sempre","lo cancella","lo rende illeggibile"],0,445),
 ("v","La formula inizia sempre con =.",True,420),
 ("v","SOMMA funziona anche con celle vuote.",True,420),
 ("v","Il riferimento $A$1 cambia copiando.",False,435),
 ("v","L'ordinamento riordina le righe.",True,420),
 ("v","La formattazione cambia i valori.",False,420),
 ("v","SE dà esiti diversi per condizione.",True,420),
 ("v","I grafici si aggiornano al variare dei dati.",True,451),
 ("v","La protezione blocca le celle protette.",True,445),
 ("v","MEDIA calcola la somma totale.",False,420),
],
"b4": [
 ("m","Il pixel è…",["il punto elementare dell'immagine","un folletto","un insetto","un pesce"],0,470),
 ("m","La profondità di colore indica…",["i bit per pixel","la profondità del mare","l'altezza","il peso"],0,470),
 ("m","Il campionamento audio misura…",["valori al secondo (Hz)","la febbre","la pressione","il peso"],0,470),
 ("m","Il formato MP3 è…",["audio compresso e leggero","video","immagine","testo"],0,485),
 ("m","Il formato WAV è…",["audio non compresso e pesante","audio leggero","video","testo"],0,485),
 ("m","Il formato MP4 è…",["video diffuso sul web","solo audio","solo testo","un virus"],0,485),
 ("m","Il GIF è…",["immagini animate semplici","un formato audio","un virus","un documento"],0,485),
 ("m","Il PNG…",["supporta la trasparenza","non comprime mai","è solo foto","è un video"],0,485),
 ("m","Il ridimensionamento…",["cambia le dimensioni in pixel","cambia idea","cambia canale","cambia casa"],0,490),
 ("m","Il ritaglio (crop)…",["seleziona una porzione dell'immagine","potatura piante","taglio capelli","cucito"],0,490),
 ("m","La rotazione…",["raddrizza l'orizzonte storto","fa girare la testa","un balletto","una giostra"],0,490),
 ("m","Luminosità e contrasto sono…",["correzioni base dell'immagine","gusti di gelato","colori di auto","taglie"],0,490),
 ("m","I livelli…",["sovrappongono gli elementi","piani di un palazzo","ripiani","livelle"],0,490),
 ("m","Il testo sulle immagini crea…",["titoli e didascalie","confusione sempre","errori","virus"],0,490),
 ("m","Lo storyboard è…",["il piano delle scene del video","un gioco da tavolo","un libro","un film già fatto"],0,510),
 ("m","Il taglio…",["elimina parti indesiderate","ferisce","cucina","cuce"],0,510),
 ("m","Le transizioni sono…",["passaggi animati tra scene","traslochi","viaggi","passaggi a livello"],0,510),
 ("m","Titoli di testa e coda sono…",["apertura e chiusura del video","cappelli","code di animali","titoli di giornale"],0,510),
 ("m","L'esportazione produce…",["il file finale da condividere","un documento cartaceo","niente","un errore"],0,510),
 ("m","Il 16:9 è…",["il formato panoramico","un voto","una data","un'ora"],0,510),
 ("m","Bilanciare l'audio significa…",["equilibrare voci, musica ed effetti","pesare le casse","comprare cuffie","alzare tutto al massimo"],0,502),
 ("v","Il PNG supporta la trasparenza.",True,485),
 ("v","L'MP3 è audio compresso.",True,485),
 ("v","Il WAV occupa meno dell'MP3.",False,485),
 ("v","Il crop allarga l'immagine.",False,490),
 ("v","I livelli sovrappongono elementi.",True,490),
 ("v","Lo storyboard pianifica le scene.",True,510),
 ("v","Il 16:9 è panoramico.",True,510),
 ("v","Il testo nelle immagini non serve mai.",False,490),
 ("v","Le transizioni collegano le scene.",True,510),
],
}

def pdf_text(pages):
    r = PdfReader(PDF)
    out = []
    for p in pages:
        if 0 <= p < len(r.pages):
            out.append(r.pages[p].extract_text() or '')
    return '\n'.join(out)

def main():
    if not os.path.exists(PDF):
        print('PDF non trovato:', PDF); sys.exit(1)
    r = PdfReader(PDF)
    print('PDF pagine:', len(r.pages))
    quiz = {"app": "InfoComm Quiz · stile INVALSI", "source_pdf": os.path.basename(PDF),
            "minutes_per_quiz": 12, "pass_score": 6, "modules": []}
    for mid, title, book_start, book_end in MODULES_META:
        p0, p1 = book_start + OFFSET, book_end + OFFSET
        text = pdf_text(range(p0, min(p1 + 1, len(r.pages))))
        low = text.lower()
        missing = [k for k in KEYWORDS[mid] if k.lower() not in low]
        if missing:
            print('AVVISO', mid, 'keyword mancanti:', missing)
        else:
            print('OK', mid, 'pagine pdf', p0, '-', min(p1, len(r.pages)-1), 'caratteri', len(text))
        qs = []
        for i, item in enumerate(Q[mid] + Q_EXTRA.get(mid, []), 1):
            typ = item[0]
            if typ == 'm':
                _, q, opts, ans, bookpg = item
                qs.append({"id": f"{mid}-q{i:02d}", "type": "multiple",
                           "q": q, "options": opts, "answer": ans,
                           "source": f"InfoComm, pag. {bookpg}"})
            else:
                _, q, ans, bookpg = item
                qs.append({"id": f"{mid}-q{i:02d}", "type": "truefalse",
                           "q": q, "answer": bool(ans),
                           "source": f"InfoComm, pag. {bookpg}"})
        quiz["modules"].append({"id": mid, "title": title,
            "book_pages": [book_start, book_end], "minutes": 12,
            "questions": qs})
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(quiz, open(OUT, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    n = sum(len(m['questions']) for m in quiz['modules'])
    print('Scritto', OUT, '-', len(quiz['modules']), 'moduli,', n, 'domande')

if __name__ == '__main__':
    main()
