export interface Question {id:string; q:string; options:string[]; answer:number; explanation:string; topic:string; difficulty:string; source:string; bookPage:number; pdfPage:number; type:string}
export interface Module {id:string; title:string; description:string; book_pages:number[]; questions:Question[]}
export interface Bank {version:string; modules:Module[]}
export interface Config {module:string; mode:'practice'|'exam'; count:number; minutes:number; pass:number; seed:string; label:string}
export interface Session {id:string; bankVersion:string; config:Config; questions:Question[]; answers:Record<string,number>; checked:string[]; index:number; started:number; deadline:number|null; finished:number|null; reason?:string}
export function random(seed:string){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return ()=>{h+=0x6D2B79F5;let t=Math.imul(h^(h>>>15),h|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
export function shuffle<T>(items:T[],rng:()=>number):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function bounded(raw:unknown,min:number,max:number,fallback:number){const n=Number(raw);return raw!==null&&raw!==''&&Number.isFinite(n)?Math.min(max,Math.max(min,Math.floor(n))):fallback;}
export function normalize(raw:Partial<Config>,bank:Bank):Config{const m=bank.modules.find(m=>m.id===raw.module)||bank.modules[0];return {module:m.id,mode:raw.mode==='exam'?'exam':'practice',count:bounded(raw.count,1,m.questions.length,10),minutes:bounded(raw.minutes,1,120,15),pass:bounded(raw.pass,1,10,6),seed:String(raw.seed||crypto.randomUUID()).slice(0,100),label:String(raw.label||'').slice(0,80)};}
export function makeSession(config:Config,bank:Bank,now=Date.now(),pool?:Question[]):Session{const rng=random(config.seed),m=bank.modules.find(m=>m.id===config.module)!;const questions=shuffle(pool||m.questions,rng).slice(0,config.count).map(q=>{const order=shuffle(q.options.map((_,i)=>i),rng);return {...q,options:order.map(i=>q.options[i]),answer:order.indexOf(q.answer)};});return {id:crypto.randomUUID(),bankVersion:bank.version,config:{...config,count:questions.length},questions,answers:{},checked:[],index:0,started:now,deadline:config.mode==='exam'?now+config.minutes*60000:null,finished:null};}
export function summary(s:Session){const correct=s.questions.filter(q=>s.answers[q.id]===q.answer).length;const answered=s.questions.filter(q=>Object.hasOwn(s.answers,q.id)).length;const grade=correct/s.questions.length*10;return {correct,answered,total:s.questions.length,wrong:answered-correct,missing:s.questions.length-answered,grade,passed:grade>=s.config.pass};}
export function expired(s:Session,now=Date.now()){return !s.finished&&s.deadline!==null&&now>=s.deadline;}
export function configParams(c:Config){return new URLSearchParams({mod:c.module,mode:c.mode,n:String(c.count),min:String(c.minutes),pass:String(c.pass),seed:c.seed,label:c.label}).toString();}
export function escapeHtml(x:unknown){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export interface Report {format:'infocomm-result-v2';id:string;bankVersion:string;module:string;label:string;student:string;mode:string;started:number;finished:number;total:number;correct:number;grade:number;pass:number;answers:{id:string;selected:number|null}[]}
export function report(s:Session,student=''):Report{const t=summary(s);return {format:'infocomm-result-v2',id:s.id,bankVersion:s.bankVersion,module:s.config.module,label:s.config.label,student:student.trim().slice(0,80),mode:s.config.mode,started:s.started,finished:s.finished||Date.now(),total:t.total,correct:t.correct,grade:t.grade,pass:s.config.pass,answers:s.questions.map(q=>({id:q.id,selected:s.answers[q.id]===undefined?null:s.answers[q.id]}))};}
export function parseReport(value:unknown):Report{const r=value as Report;if(!r||r.format!=='infocomm-result-v2'||typeof r.id!=='string'||typeof r.bankVersion!=='string'||typeof r.module!=='string'||typeof r.student!=='string'||typeof r.label!=='string'||!['exam','practice'].includes(r.mode)||!Number.isFinite(r.started)||!Number.isFinite(r.finished)||r.finished<r.started||!Number.isInteger(r.total)||r.total<1||r.total>400||!Number.isInteger(r.correct)||r.correct<0||r.correct>r.total||!Number.isFinite(r.grade)||Math.abs(r.grade-r.correct/r.total*10)>0.00001||!Number.isInteger(r.pass)||r.pass<1||r.pass>10||!Array.isArray(r.answers)||r.answers.length!==r.total||new Set(r.answers.map(a=>a.id)).size!==r.total||r.answers.some(a=>typeof a.id!=='string'||!(a.selected===null||Number.isInteger(a.selected)&&a.selected>=0&&a.selected<=3)))throw Error('Formato del risultato non valido');return r;}
export function csvCell(value:unknown){const s=String(value);return '"'+(/^[=+@\-\t\r\n]/.test(s)?"'":"")+s.replaceAll('"','""')+'"';}
